---
- hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Install dipendenses
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: aggiungi repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Start docker daemon
      service:
        name: docker
        state: started
        enabled: yes
      ignore_errors: yes 
    
    - name: Create group docker
      group:
        name: docker
        state: present
      when: "'docker' in groups"

    - name: Add user to group
      user:
        name: "{{ ansible_facts['env']['SUDO_USER'] }}"
        groups: docker
        append: yes
      notify:
        - restart_groups

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted

    - name: restart_groups
      shell:
        cmd: "newgrp docker"
