---
- hosts: server001
  gather_facts: False
  become: true
  pre_tasks:
    - name: check host
      shell: | 
        hostname
      register: out
      tags: 
        - info
    - name: Show host
      debug:
        msg: "{{ out.stdout }}"
      tags: 
        - info
  roles:
    - server