---
- import_playbook: ci_docker.yaml

# DEPLOY ROLS
- hosts: localhost
  gather_facts: no
  become: true
  pre_tasks:
    - name: check host
      shell: | 
        hostname
      register: out
    - name: Show host
      debug:
        msg: "{{ out.stdout }}"

  roles:
    - server
