---
- hosts: localhost
  gather_facts: no
  become: true
  sudo: yes
  pre_tasks:
    - name: check host
      shell: | 
        hostname
      register: out
    - name: Show host
      debug:
        msg: "{{ out.stdout }}"

  roles:
    - server
    
  post_tasks:
    include: ci_docker.yaml