---
- hosts: localhost
  gather_facts: False
  become: true
  tasks:
    - name: Install dipendenses
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Import GPG key
      shell:
        cmd: curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add - && sudo add-apt-repository "deb https://download.sublimetext.com/ apt/stable/"

    - name: install sublime
      shell:
        cmd: sudo apt update -y && sudo apt install sublime-text -y

