---
apt_packages:
  - tmux
  - vim 
  - mosh 
  - htop 
  - git 
  - curl 
  - wget 
  - unzip 
  - zip
  - tree
  - default-jre
  - default-jdk

s_pass: $6$51vrG8IYVybgMHXY$5NAOO2BGKQfI24v.xEpo93p3EjHrB6UDDlHLsNoX/T4FdsMusXgs3jiOMBqVMzT/YndXH5jy.ZVtXEvEvI7Vx1