---
- name: Update packages
  shell:
    cmd: apt update -y

- name: Install packages
  apt:
    name: "{{ apt_packages }}"
    state: latest
    update_cache: yes

- name: Add foldef for code
  file: 
    path: /code 
    state: directory
    ownew: "{{ sudo_user }}"

- name: Add foldef for jenkins
  file: 
    path: /jenkins 
    state: directory
  
# - name: Add any alias
  # shell:
    # cmd: echo "alias cls='clear'" >> ~/.bashrc

- name: Add the sudo user
  user:
    name: "{{ sudo_user }}"
    shell: /bin/bash
    password: "{{s_pass}}"
    groups: sudo
  tags: 
    - add_user

- name: Add user www to sudoers
  shell:
    cmd: echo ""{{ sudo_user }}"  ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/"{{ sudo_user }}"
  tags: 
    - add_user
