---
  - name: Update packages
    shell:
      cmd: apt update -y
    tags:
      - install_apps
  
  - name: Install LAMP packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
      - apache2
      - mysql-server 
      - python3-pymysql 
      - php
      - php-mysql
      - libapache2-mod-php
    tags:
      - install_apps

  - name: Create document root
    file:
      path: "/var/www/{{ http_host }}"
      state: directory
      owner: "{{ app_user }}"
      mode: '0755'
    tags:
      - apache

  - name: Set up Apache virtualhost
    template:
      src: "fanDOK.system.conf.j2"
      dest: "/etc/apache2/sites-available/{{ http_conf }}"
    notify: Reload Apache
    tags:
      - apache
  
  - name: Enable new site
    shell: /usr/sbin/a2ensite {{ http_conf }}
    notify: Reload Apache
    tags:
      - apache

 
  - name: Clone src
    git:
      repo: "{{ app_repo }}"
      dest: "{{ app_path }}"
      version: "{{ app_version }}"
      accept_hostkey: yes
      update: no
    tags:
      - git
  
  - name: Copy code
    copy:
      src: "{{app_path}}/src/public_html/"
      dest: "{{http_path}}"
      remote_src: yes 
      directory_mode: yes
    tags:
      - git_copy
      - git

  # ------------ SQL TEST ------------
  # - name: Sets the root password
  #   mysql_user:
  #     name: root
  #     password: "{{ mysql_root_password }}"
  #     login_unix_socket: /var/run/mysqld/mysqld.sock
  #   tags:
  #     - sql_test
      
  # UFW Configuration
  - name: "UFW - Allow HTTP on port {{ http_port }}"
    ufw:
      rule: allow
      port: "{{ http_port }}"
      proto: tcp

  # PHP Info Page
  - name: Sets Up PHP Info Page
    template:
      src: "info.php.j2"
      dest: "/var/www/{{ http_host }}/info.php"
    tags:
      - test_php

    # ------------ SQL TEST ------------
  - name: MySQL. Install and setup
    template:
      src: my.cnf.j2
      dest: ~/.my.cnf
      owner: "{{app_user}}"
      mode: 0600
    notify:
      - restart mysql
    tags:
      - sql
      - sql_config
    
  # - meta: flush_handlers
  
  - mysql_db:
      name: "{{ app_db_name }}"
      state: present
      encoding: utf8
    tags:
      - sql
      - sql_create
    
  - mysql_user:
      name: "{{ app_db_user }}"
      password: "{{ app_db_pass }}"
      priv: "{{ app_db_name }}.*:ALL"
    # no_log: "{{ hide_logs | default(True) }}"
    tags:
      - sql
      - sql_user
  

  
  # - name: Config database
  #   template:
  #     src: database.yml.j2
  #     dest: "{{ app_home }}/config/database.yml"
  #   tags:
  #     - db::config
 
  # - name: Configuration files for virtualhost
  #   template:
  #     src: redmine.site.conf.j2
  #     dest: "/etc/apache2/sites-enabled/redmine.site.conf"
  #   notify:
  #     - restart apache
  #   tags:
  #     - apache::setup
  
  # - meta: flush_handlers